server {
    listen 80;
    server_name 47.104.224.159;

    location = /OrangeSite {
        return 301 /OrangeSite/;
    }

    location ^~ /OrangeSite/ {
        alias /var/www/OrangeSite/;
        try_files $uri $uri/ /OrangeSite/index.html;

        expires -1;
        add_header Cache-Control "no-store";
    }

    location ^~ /api/ {
        proxy_pass http://210.44.150.112:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
